import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { alu32 } from '../rtl/alu32.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cssName = (name) => `--${name}`;
const pins = (ports) => Object.entries(ports).flatMap(([name, port]) =>
  Array.from({ length: port.width }, (_, index) => port.width === 1 ? name : `${name}-${index}`));
const compile = (node) => {
  switch (node.op) {
    case 'ref': return `var(${cssName(node.name)})`;
    case 'lit': return String(node.value);
    case 'add': return `calc(${node.args.map(compile).join(' + ')})`;
    case 'sub': return `calc(${compile(node.left)} - ${compile(node.right)})`;
    case 'mul': return `calc(${node.args.map(compile).join(' * ')})`;
    case 'div': return `calc(${compile(node.left)} / ${compile(node.right)})`;
    case 'mod': return `mod(${compile(node.left)}, ${compile(node.right)})`;
    case 'floor': return `round(down, ${compile(node.value)}, 1)`;
    case 'min': return `min(${node.args.map(compile).join(', ')})`;
    case 'abs': return `abs(${compile(node.value)})`;
    default: throw new Error(`unknown IR op ${node.op}`);
  }
};

const inputPins = pins(alu32.inputs);
const statePins = pins(alu32.state);
const signalPins = Object.keys(alu32.signals);
const properties = [...inputPins, ...statePins, ...signalPins];
const registrations = properties.map((name) => `@property ${cssName(name)} {\n  syntax: "<number>";\n  inherits: false;\n  initial-value: 0;\n}`).join('\n\n');
const defaults = [...inputPins, ...statePins].map((name) => `  ${cssName(name)}: 0;`).join('\n');
const netlist = Object.entries(alu32.signals).map(([name, expression]) => `  ${cssName(name)}: ${compile(expression)};`).join('\n');
const css = `/* Generated by scripts/generate.mjs. Do not hand-edit. */\n${registrations}\n\n.css386-chip {\n${defaults}\n${netlist}\n}\n`;
const manifest = {
  version: 1,
  name: alu32.name,
  inputs: alu32.inputs,
  state: alu32.state,
  signals: signalPins,
  latches: alu32.latches
};

fs.mkdirSync(path.join(root, 'generated'), { recursive: true });
fs.writeFileSync(path.join(root, 'generated', 'alu32.css'), css);
fs.writeFileSync(path.join(root, 'generated', 'alu32.manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`generated ${properties.length} registered one-bit nets, ${css.length} CSS bytes`);
